### ISSUE TITLE
Not able to resolve  GoogleClientManager.Initialize(this) in Android and GoogleClientManager.Initialize(); in iOS

### ISSUE THREAD

**Issue by hashimks** [CrossGeeks/GoogleClientPlugin#1]
Hello,

I am using the plugin 1.0.3-beta in my Xamarin forms app developed in .net standard 2.  I added the nuget to whole solutions (Portable, Droid and iOS). However I am not able to resolve 

GoogleClientManager.Initialize(this) in Android and GoogleClientManager.Initialize(); in iOS. I am really stuck here. Can you please help me out?

Thanks,
Hashim K S

**Comment by hashimks** [comment]
Can anyone please help me?

**Comment by hashimks** [comment]
Hello????

**Comment by hashimks** [comment]
@Pujolsluis I had tried initially with 1.0.4 version and had the same issue. So when i checked the sample I could see it as 1.0.3. So i used that version and the same issue. I tried the sample aqs well and that also did not work

**Comment by hashimks** [comment]
@Pujolsluis Hello.. Did you get a chance to check this?

**Comment by Pujolsluis** [comment]
Hey @hashimks, Yes I'm working on the updates right now, will have the stable version by tomorrow.

**Comment by Pujolsluis** [comment]
Hey @hashimks, Today we released the v1.0.9-beta in which I have personally validated that now everything is up and running, you should be able to use the plugin without any problems on iOS and Android, just follow the Setup Guides on the repo and it should work.
