### ISSUE TITLE
Add CurrentUser property to IGoogleClientManager

### ISSUE THREAD

**Issue by RomaRudyak** [CrossGeeks/GoogleClientPlugin#10]
**Is your feature request related to a problem? Please describe.**
I need to access current login user data not triggering Login each time.

**Describe the solution you'd like**
Add property for current login user to IGoogleClientManager. If it is null user not login.
Android and iOS has native API for getting login user.

**Comment by rdelrosario** [comment]
This was added on https://www.nuget.org/packages/Plugin.GoogleClient/2.0.18-beta

Will be included on next official version
