### ISSUE TITLE
No exception if Plugin used before Initialized triggered

### ISSUE THREAD

**Issue by RomaRudyak** [CrossGeeks/GoogleClientPlugin#12]
**Describe the bug**
Possibility to use `CrossGoogleClient.Current` before `GoogleClientManager.Initialize` called

**To Reproduce**
1. Create application as from guide
2. Remove GoogleClientManager.Initialize in OnCreate in Android
3. Call CrossGoogleClient.Current.LoginAsync();

**Expected behavior**
There must be throw NotInitializedException when CrossGoogleClient.Current requested.

**Information (please complete the following information):**
 - OS: Android/iOS
 - Version: 1.0.14

**Comment by Pujolsluis** [comment]
Hey @RomaRudyak ,

I'm currently adding support for this issue, still need to finish polishing it on iOS but it will be live on the next stable release of the plugin.

**Comment by Pujolsluis** [comment]
Hey @RomaRudyak ,

Support for this issue has been added on the new stable release of the plugin v1.1.0, I will now close this issue Thanks for reporting it and collaborating 💪.
