### ISSUE TITLE
Exception Occurred

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [CrossGeeks/GoogleClientPlugin#14]
The Google Sign In could not complete it's process correctly occur after click on login button (GoogleClientBaseException)

**Comment by AhmedAdelGadElkareeem** [comment]
@Pujolsluis 
Describe the bug
Google Client Base Exception Occur and The Google Sign In could not complete it's process correctly message appear when call CrossGoogleClient.Current.LoginAsync();  in login button 

Expected behavior
my data returned after complete login

Screenshots
![error](https://user-images.githubusercontent.com/30314037/43383480-6e5cd038-93db-11e8-9cfc-ff2e6d089dd4.PNG)

Smartphone (please complete the following information):
device :- Android Emulator Api 19 kit-kat

**Comment by stealthcold** [comment]
Same here.. Any idea how to fix that?

**Comment by stealthcold** [comment]
Ops, sorry. I changed my app package name. But forgot to change in Firebase console.
Now its working.

**Comment by Pujolsluis** [comment]
@AhmedAdelGadElkareeem 

Please verify your setup steps are correct, this error indicated that something is missing on the setup.

**Comment by Theusminha** [comment]
Hello guys, sorry for reviving this topic but I downloaded the latest version of the project and I get the same error, I didn't change anything. Could you help me Pujolsluis?

**Comment by jadson-medeiros** [comment]
Guys, I get the same error too, someone, please, can help me with this problem?

**Comment by Pujolsluis** [comment]
Hi Guys, @Theusminha @jadson-medeiros  you must follow the setup guides and do the appropriate changes on the sample project to get it running with your firebase console project

**Comment by jadson-medeiros** [comment]
I tried everything.... But I'll configure the firebase and running the application again

**Comment by DavidHouses** [comment]
Hello Goodnight.

I have already followed all the steps to be able to log in but I get the message "Google login could not complete your process correctly".

1- configure application in google for android
![Captura de Pantalla 2019-06-01 a la(s) 23 32 54](https://user-images.githubusercontent.com/20448864/58756922-b9605500-84c6-11e9-8eb8-ffaa19abe7f2.png)

2- configure application in firebase
3 - enter the code that is with the example
![Captura de Pantalla 2019-06-01 a la(s) 23 35 19](https://user-images.githubusercontent.com/20448864/58756925-dac14100-84c6-11e9-8642-707f855fe488.png)

![Captura de Pantalla 2019-06-01 a la(s) 23 36 09](https://user-images.githubusercontent.com/20448864/58756927-f4fb1f00-84c6-11e9-8fac-6061b325c7dd.png)


4 - Download the Google repository
![Captura de Pantalla 2019-06-01 a la(s) 23 32 27](https://user-images.githubusercontent.com/20448864/58756926-df85f500-84c6-11e9-80e0-fb7db59bdd57.png)
He keeps sending me the same message.

**Comment by syedbilalali** [comment]
I am also getting same error in xamrine forms application in Android 10. Please suggest me some solution. I am waiting...
