### ISSUE TITLE
can we have more than the Name, Email and Picture for the user ?

### ISSUE THREAD

**Issue by JonathanGermain** [CrossGeeks/GoogleClientPlugin#2]
i wanna know if is possible to have the token ?

**Comment by Pujolsluis** [comment]
Yes, we will be exposing the Auth Token of the user on the next release.

As for what extra data, right now we are exposing the basic profile Google Sign In offers. But what other information that the client offers would you like to see?

**Comment by JonathanGermain** [comment]
For now just the userid

**Comment by Pujolsluis** [comment]
@JonathanGermain Will be working on this feature today, a new version of the plugin will be available tomorrow Jul 2.

**Comment by Pujolsluis** [comment]
Hey @JonathanGermain ,

We just released a version of the plugin, in which we have the first take at this feature you can test it out and give us your feedback by downloading the latest version of the plugin v1.0.14 (@RomaRudyak here is the update on the token feature you were asking about too).
