### ISSUE TITLE
LoginAsync hides app on Android

### ISSUE THREAD

**Issue by IlyaLehchylin** [CrossGeeks/GoogleClientPlugin#20]
**Describe the bug**
When I'm calling `LoginAsync`, it hides my app. Then the popup with google accounts is shown and after choosing one nothing happens. The app doesn't crash.

**To Reproduce**
1. Call `LoginAsync();`

**Expected behavior**
The popup doesn't hide application and the popup is shown on the same page where it was called.

**Screenshots**

![screenshot_2018-11-29-12-09-55](https://user-images.githubusercontent.com/15575416/49211470-b0d07a00-f3d0-11e8-9658-4a9f5becc0ba.png)

![screenshot_2018-11-29-12-09-45-2](https://user-images.githubusercontent.com/15575416/49211487-bcbc3c00-f3d0-11e8-9be8-87e1ea56c5d5.png)

**Smartphone (please complete the following information):**
 - Device: Lenovo P70-A
 - OS: Android
 - Version 5.1

**Additional context**

```
var googleClient = CrossGoogleClient.Current;
var response = await googleClient.LoginAsync(); // stuck here
var data = response.Data;
```

Firebase project is configured correctly.
Also tried to use `Device.BeginInvokeOnMainThread`.

**Comment by Pujolsluis** [comment]
Hey @IlyaLehchylin ,

Where you able to replicate this issue on other devices?

**Comment by IlyaLehchylin** [comment]
Tried only on Lenovo.

вс, 9 дек. 2018 г. в 19:12, Luis Pujols <notifications@github.com>:

**Comment by Pujolsluis** [comment]
Could you please try the sample app and verify if this behavior is happening on your device too, or try test your app in 2 different devices and give us an update on the situation.

Thanks!

**Comment by Pujolsluis** [comment]
Will proceed to close this Issue, since there is no update on it.

**Comment by IlyaLehchylin** [comment]
@Pujolsluis Sorry for the late reply.. I have cloned repo and have installed the demo app. There wasn't the bug like it was in my application. The difference between the sample and my project is that I'm using NetStandard 2.0 library, not the Shared project.
