### ISSUE TITLE
Not able to get AccessToken and RefreshToken

### ISSUE THREAD

**Issue by Lemedon** [CrossGeeks/GoogleClientPlugin#22]
**Describe the bug**
Hi! , I am not able to receive the access and refresh tokens with this library.
I wanted to exchange the `ActiveToken` to access and refresh token directly from my app by calling this endpoint [
https://developers.google.com/identity/protocols/OAuth2WebServer#exchange-authorization-code](url) but I only receive `access_token` with expires after 1 hour and without `refresh_token`. How can I access Google services like Gmail or Drive by using this library? Maybe I’m missing some authentication flow? 
Thanks for help :/

**Comment by Pujolsluis** [comment]
Hey @Lemedon ,

To access different API services from your backend server you need to initialize the plugin the scopes you want to use, you can read more about the topic here https://developers.google.com/identity/sign-in/android/offline-access

I believe @RomaRudyak can help you out with any questions about this, he collaborated with adding support for it on the plugin to make use of it on his projects. 💪 

```cs
// Initialize method signature on Android
public static void Initialize(
            Activity activity,
            string serverClientId = null,
            string clientId = null,
            Api[] apis = null,
            string[] scopes = null)
```

```cs
// Initialize method signature on iOS
public static void Initialize(string clientId = null, params string[] scopes)
```

**Comment by RomaRudyak** [comment]
@Lemedon Hi,

sorry for late replay.

1. Do you using some kind of IoC containers or Productivity Frameworks for your project?
2. Do you use web key as clientId ?

**Comment by Lemedon** [comment]
1. Yes Im using MvvmCross
2. I passing clientId from auto-generated google web application as parameter to Initialize() method as @Pujolsluis has mentioned before but it's returns AccessToken only for iOS version. I would like to receive auto refreshed `access_token` every time on every platform . Is that possible?

**Comment by Pujolsluis** [comment]
Hey @Lemedon ,

Any updates on your issue?. Thanks for all the support @RomaRudyak💪

**Comment by Pujolsluis** [comment]
Will proceed to close this issue, since there are no further updates.

Thanks again @RomaRudyak for your support🙌.

**Comment by ecoukraine** [comment]
Hi guys,
thanks a lot for the plugin.
Would you be kind to share how to get AccessToken from User object? It's not there, or I've missed something?

Looking forward to hearing from you
