### ISSUE TITLE
Java.Lang.ClassNotFound Exception calling CrossGoogleClient.Current

### ISSUE THREAD

**Issue by edhalsim** [CrossGeeks/GoogleClientPlugin#25]
**Describe the bug**
When running my Xamarin.Forms app using code copied from the client sample, I'm getting this error.
Java.Lang.ClassNotFoundException: <Timeout exceeded getting exception details> occurred

**To Reproduce**
F5 running the debugger.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Android Emulator x86 Oreo (8.1)

**Additional context**
I created my app. in Google Firebase and copied the google-services.json to the root of my Android project.

**Comment by stealthcold** [comment]
Hi,

If your emulator has the Google Apis, you could try add Xamarin.GooglePlayServices.Auth package to your android project and then Clean/Build.

**Comment by stealthcold** [comment]
Hi @edhalsim ,

Check if your app package name it's the same in your project and Firebase console.
Also, can you see if [this solution](https://github.com/CrossGeeks/GoogleClientPlugin/issues/16#issuecomment-416491293) is applicable to you?

**Comment by edhalsim** [comment]
> Hi @edhalsim ,
> 
> Check if your app package name it's the same in your project and Firebase console.
> Also, can you see if [this solution](https://github.com/CrossGeeks/GoogleClientPlugin/issues/16#issuecomment-416491293) is applicable to you?

I think that worked.  I had to update the package name in the AndroidManifest.xml file.  Now it appears to login successfully, although the token is null;  not sure if that's an issue or not.  Thanks again for the help!

**Comment by stealthcold** [comment]
Hi @edhalsim ,

Maybe the issue with the token is related to [this question](https://github.com/CrossGeeks/GoogleClientPlugin/issues/17). Can you take a look?

Thanks,

**Comment by edhalsim** [comment]
I haven't has the time to investigate the null token.  I'm not even entirely sure what it's supposed to do.  I'm getting authenticated and that's good enough for me now.
