### ISSUE TITLE
A Network error Occurred. Retrying should resolve the problem

### ISSUE THREAD

**Issue by ndondapati** [CrossGeeks/GoogleClientPlugin#27]
Downloaded the solution; just removed Ios and only included Android App; updated the manifest file, got new google service json file; do have sha1 as well; Build run fine; on login using gmail got below error.
![andloginissue](https://user-images.githubusercontent.com/45668979/50616197-0fe04d80-0ead-11e9-99ab-599a47b78cf7.jpg)

**Comment by Pujolsluis** [comment]
Hey @ndondapati ,

Please verify you have added the permissions required to the Android project and that your device has internet available.

**Comment by Pujolsluis** [comment]
Hey @ndondapati , any updates on this issue?

**Comment by ndondapati** [comment]
Nope was not able to resolve.

**Comment by Gaburiere** [comment]
i was having the same issue on a project running on android emulator. Goes well running on device. Maybe it is caused by some background data settings on emulator.
