### ISSUE TITLE
Value cannot be null. Parameter name: path

### ISSUE THREAD

**Issue by Martins-74** [CrossGeeks/GoogleClientPlugin#28]
HI, thanks for the amazing plugin, but i keep getting the same error on iOS while on android i fully functional.
The error i get is when i launch the app on iOS when calling the GoogleClientManager.Initialize(); it trows an error saying "Value cannot be null. Parameter name: path"

![captura de ecra 2019-01-10 as 14 42 18](https://user-images.githubusercontent.com/20977088/50975906-8a7d1e80-14e6-11e9-85d5-55c9295855d6.png)

**Desktop:**
 - OS: iMac High Sierra

**Smartphone (please complete the following information):**
 - Device: iPhone6 Plus
 - OS: 12

**Comment by Pujolsluis** [comment]
Hey @Martins-74 ,

We are glad you enjoy using our plugin🙌😊, this error might be by an incomplete setup of the plugin in the project, please verify you followed the setup guide for iOS correctly and that the GoogleService-Info.plist has it's build action set to BundleResource.

**Comment by Martins-74** [comment]
Thanks, the problem was i forgot to set the action to BundleResource 😅, after that was set all went fine.
