### ISSUE TITLE
OnLogin Event is never Fired, nothing happens

### ISSUE THREAD

**Issue by XceSx6** [CrossGeeks/GoogleClientPlugin#34]
LoginAsync() is triggered, testing on Android..
A box pops open to select a User to continue with, after that nothing happens ..
OnLogin is never fired, no permissions are requested although the Scope is filled.
                 _CrossGoogleClient.Current.OnLogin += CrossGoogleClient_OnLogin;
                 var googleUser = CrossGoogleClient.Current.LoginAsync();_

Why doesn't anything happen after the account selection ?
Did I miss something ?? I followed the Setup as described.

**Comment by Pujolsluis** [comment]
Hey @XceSx6,

Did you get a look at the Sample project on the repo? could you verify that you have the last version and that the iOS and Android setup are completed correctly?

You could use the sample project to test that is working by swapping out the .json file, and adding your own client ID and .json file

**Comment by XceSx6** [comment]
Hey Luis,

 

I did look at the Sample project, but after replacing the JSON and testing it still does nothing, same as before.. Click Login but nothing happens.

On my own project I followed the Guidelines on GitHub, and when i click Login on my button it does popup an Account selector, but then nothing.

 

So I don’t know what I’m doing wrong here :x

Once i get through my Login, I can help @nguyenthanhliemfc <https://github.com/nguyenthanhliemfc>  with using the ActiveToken to authenticate his Google Services.

 

Kind regards, we can Skype if you like, its “bourgeois.dirk@outlook.com”

**Comment by Pujolsluis** [comment]
Problem Solved, by configuring correctly the project following the guides.

**Comment by breula** [comment]
And the guide is?

**Comment by BourgeoisDirk** [comment]
I agree with @breula , no idea what the Fix is..
Although following the Guide, the OnLogin event never fires.

**Comment by breula** [comment]
> I agree with @breula , no idea what the Fix is..
> Although following the Guide, the OnLogin event never fires.

After install all Nupackages installed in the sample, etc.. etc.. At least now is firing but not "Plugin.GoogleClient.Shared.GoogleClientBaseException: '10: '" Same happens running the sample.

**Comment by breula** [comment]
Yep. simple does not works even informing the finger print on the Fire Base till getting Plugin.GoogleClient.Shared.GoogleClientBaseException: '10: 'At least the Facebook one works  Let's go try to find another way, if succed i will post solution here.

**Comment by breula** [comment]
Done, I used in a Command as:

public async void LoginWithGoogle()
{
	switch (Device.RuntimePlatform)
	{
		case Device.iOS:
			CrossGoogleClient.Current.OnLogin += (s, a) =>
			{
				switch (a.Status)
				{
					case GoogleActionStatus.Canceled:
						App.Current.MainPage.DisplayAlert("Cancelado", a.Message, "OK");
						break;
					case GoogleActionStatus.Unauthorized:
						App.Current.MainPage.DisplayAlert("Não autorizado", a.Message, "OK");
						break;
					case GoogleActionStatus.Completed:
						break;
					case GoogleActionStatus.Error:
						App.Current.MainPage.DisplayAlert("Erro", a.Message, "OK");
						break;
					default:
						break;
				}
			};
			break;
		case Device.Android:
			googleClientManager.OnLogin += OnLoginCompleted;
			try
			{
				await googleClientManager.LoginAsync();
			}
			catch (GoogleClientSignInNetworkErrorException e)
			{
				await App.Current.MainPage.DisplayAlert("Error", e.Message, "OK");
			}
			catch (GoogleClientSignInCanceledErrorException e)
			{
				await App.Current.MainPage.DisplayAlert("Error", e.Message, "OK");
			}
			catch (GoogleClientSignInInvalidAccountErrorException e)
			{
				await App.Current.MainPage.DisplayAlert("Error", e.Message, "OK");
			}
			catch (GoogleClientSignInInternalErrorException e)
			{
				await App.Current.MainPage.DisplayAlert("Error", e.Message, "OK");
			}
			catch (GoogleClientNotInitializedErrorException e)
			{
				await App.Current.MainPage.DisplayAlert("Error", e.Message, "OK");
			}
			catch (GoogleClientBaseException e)
			{
				await App.Current.MainPage.DisplayAlert("Error", e.Message, "OK");
			}
			break;
	}
}

private void OnLoginCompleted(object sender, GoogleClientResultEventArgs<Plugin.GoogleClient.Shared.GoogleUser> loginEventArgs)
{
	if (loginEventArgs.Data != null)
	{
		Plugin.GoogleClient.Shared.GoogleUser googleUser = loginEventArgs.Data;
		//User.Name = googleUser.Name;
		//User.Email = googleUser.Email;
		//User.Picture = googleUser.Picture;
		var GivenName = googleUser.GivenName;
		var FamilyName = googleUser.FamilyName;

		Debug.WriteLine(googleUser.Email);
		IsLoggedIn = true;

		var token = CrossGoogleClient.Current.AccessToken;
		Token = token;
	}
	else
	{
		App.Current.MainPage.DisplayAlert("Error", loginEventArgs.Message, "OK");
	}

	googleClientManager.OnLogin -= OnLoginCompleted;
}

Plus add "**Entitlements.plist**" as "**BundleResource**" in **Build Action** and choosen "**Entitlements.plist**" on Custom Entitlements for IOS Project

- IOS works 100%
- Android till got Erro "**10;**"
