### ISSUE TITLE
Java.Lang.ClassNotFoundException: com.google.android.gms.auth.api.Auth

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [CrossGeeks/GoogleClientPlugin#35]
![Untitled](https://user-images.githubusercontent.com/17796649/58265349-ab655280-7da9-11e9-874b-fe682b31ac76.png)

**Comment by Pujolsluis** [comment]
Hey @nguyenthanhliemfc ,
 
Please verify that you have all the dependencies for the plugin correctly installed on your project and it should work, sometimes it doesn't install them automatically.

**Comment by fewbackseven** [comment]
Install this nuget package.
.
https://www.nuget.org/packages/Xamarin.GooglePlayServices.Auth/
.
.
After you install this nuget package,the error should go away.

**Comment by Pujolsluis** [comment]
Issue will be closed since it's already solved, Thanks @fewbackseven for your support 💪
