### ISSUE TITLE
The Google Sign In Could not complete it's process 

### ISSUE THREAD

**Issue by DavidHouses** [CrossGeeks/GoogleClientPlugin#36]
> Hello Goodnight.
> 
> I have already followed all the steps to be able to log in but I get the message "Google login could not complete your process correctly".

> 
>I tried everything and I can not get it to connect with the app, I saw all the cases that were presented and even then I can not make it connect, could you help me?
>
> 1- configure application in google for android
> ![Captura de Pantalla 2019-06-01 a la(s) 23 32 54](https://user-images.githubusercontent.com/20448864/58756922-b9605500-84c6-11e9-8eb8-ffaa19abe7f2.png)
> 
> 2- configure application in firebase
> 3 - enter the code that is with the example
> ![Captura de Pantalla 2019-06-01 a la(s) 23 35 19](https://user-images.githubusercontent.com/20448864/58756925-dac14100-84c6-11e9-8642-707f855fe488.png)
> 
> ![Captura de Pantalla 2019-06-01 a la(s) 23 36 09](https://user-images.githubusercontent.com/20448864/58756927-f4fb1f00-84c6-11e9-8fac-6061b325c7dd.png)
> 
> 4 - Download the Google repository
> ![Captura de Pantalla 2019-06-01 a la(s) 23 32 27](https://user-images.githubusercontent.com/20448864/58756926-df85f500-84c6-11e9-80e0-fb7db59bdd57.png)
> He keeps sending me the same message.

**Comment by jadson-medeiros** [comment]
This Plugin work, if I'm using xamarin standard?

**Comment by DavidHouses** [comment]
Yes, I using xamarin forms 4 Standar

**Comment by fewbackseven** [comment]
same issue with me
Its showing google signin could not complete the process. 
.
.
How to handle defaultsignin exception? why does that exception occur??

![signin](https://user-images.githubusercontent.com/10475014/59155461-ae4d8c00-8aa7-11e9-9f94-19b7026e1a5e.jpg)

**Comment by lijusparkt** [comment]
Hi,
Anybody resolved this issue...?

**Comment by lijusparkt** [comment]
![Screenshot_2019-06-10-16-22-06](https://user-images.githubusercontent.com/50582733/59770381-8f2fd500-92c5-11e9-9c2f-e275dd74e2a7.png)
I'm also facing the same issue

**Comment by lijusparkt** [comment]
Hi, @Pujolsluis

**Comment by nguyenthanhliemfc** [comment]
I facing with this error. Please help!

**Comment by Pujolsluis** [comment]
Hi Guys! I will be doing possible live streaming guiding you through the process of using the sample app and using the plugin, will post more details about it tomorrow

**Comment by fewbackseven** [comment]
> 
> 
> Hi Guys! this issue is due to something missing on the requirements on the setup of the plugin, I will be doing a live stream or uploading recorded video guiding you through the process of using the sample app and using the plugin, will post more details about it tomorrow

Waiting for the solution.. Did you find one??

**Comment by ghostiq** [comment]
Same for me. Tried with debug sha1 (GoogleClientSignInFailedErrorException) and new created release sha1 as well (just GoogleClientBaseException for now).

**Comment by lijusparkt** [comment]
> Hi Guys! this issue is due to something missing on the requirements on the setup of the plugin, I will be doing a live stream or uploading recorded video guiding you through the process of using the sample app and using the plugin, will post more details about it tomorrow

@Pujolsluis Waiting ..........☺

**Comment by ghostiq** [comment]
Anyone figured it out in the meantime?
I tried with debugkey, created release key and tried to add sha1 fingerprint in firebase & google dev console (and then import project to firebase). Tried to prepare apk and uploaded manually to phone. All failed.

**Comment by luis95gr** [comment]
Anyone has information about this error?

**Comment by MaxiTalenti** [comment]
Hi, anybody resolved this issue...?

**Comment by lijusparkt** [comment]
No updates...........!😓

**Comment by jadson-medeiros** [comment]
at the moment nothing... :(

**Comment by ksevery** [comment]
I'm asking for this as well - if there is a fix for this issue, I would be happy to see it, and also to see the sample app updated - I managed to run it after updating all of the NuGet packages, but I am still faced with the same error.

**Comment by Ngoc-Quang** [comment]
Still not work on my side. Will have new version update for this?

**Comment by lijusparkt** [comment]
Hi Guys , I have just Completed the Google login .. I will share what was the problem that i have faced and how i resolved it

**Comment by nguyenthanhliemfc** [comment]
@lijusparkt Im waiting for you

**Comment by lijusparkt** [comment]
Hi guys , 
I'm using **Visual Studio for MAC**
Actually my problem was with my SHA-1 . For firebase setup ,I hope everyone is completely  done the things which describes in https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/GoogleClient/docs/GoogleFirebaseConsoleSetup.md  & also think Google developer console setup and API enabled in ON https://developers.google.com/assistant/sdk/guides/library/python/embed/config-dev-project-and-account

We have our own .jks (keystore) file and we are also generated our own SHA-1 with using this .jks file and password [  keytool -list -v -keystore "/Users/mac/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/<yourkestorename>.keystore" -alias <youralias>-storepass <yourpass> -keypass <yourpass>] (its my path)

And also you need to add the default SHA-1  in Firebase console ( Add Fingerprint) -->
Default SHA1 : Generate **Visual Studio for Mac**
keytool -list -v -keystore /Users/mac/.local/share/Xamarin/Mono\ for\ Android/debug.keystore -alias androiddebugkey -storepass android -keypass android 

Default SHA1 : Generate **Visual Studio**
keytool.exe -list -v -keystore "C:\Users\[USERNAME]\AppData\Local\Xamarin\Mono for Android\debug.keystore" -alias androiddebugkey -storepass android -keypass android


(Here "mac" is my user name & path is same for everyone who are using Mac pc) add this default
