### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by LijuDaniel** [CrossGeeks/GoogleClientPlugin#37]
**Describe the bug**
Unable to complete Login
![Screenshot_2019-06-10-16-22-06](https://user-images.githubusercontent.com/27279731/59191081-1bdae480-8b9c-11e9-8a38-6b1942f2eeb5.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pujolsluis** [comment]
Repeated Issue will proceed to close it, please refer to #36
