### ISSUE TITLE
How to subscribe OpenUrl for iOS with Google and FacebookClientPlugin at the same time?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [CrossGeeks/GoogleClientPlugin#38]
**Describe the bug**
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
{
            return FacebookClientManager.OpenUrl(app, url, options);
            return GoogleClientManager.OnOpenUrl(app, url, options);
}
Only first "return" will run
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pujolsluis** [comment]
Hey @nguyenthanhliemfc,

You just add one line after the other in the method and return whichever you like or just return true at the end of the method and ce finito! 😄
