### ISSUE TITLE
ActiveToken Returns OAuth Access Token on iOS but Returns JWT on Android

### ISSUE THREAD

**Issue by briandotdev** [CrossGeeks/GoogleClientPlugin#41]
**Describe the bug**
I'm not able to locate in the docs a definition of what the expected behavior is.  However, I've noticed that this library performs differently on iOS than it does on Android.  When using `CrossGoogleClient.Current.ActiveToken` to retrieve the active token after a successful Google Login I've noticed that on iOS this property returns an OAuth Access token however on Android it returns a JWT.

The difference here being that an OAuth Access Token must still be exchanged with the Google 
authorization server in order to obtain an authorized bearer token.  While a JWT is a fully signed authorization that can be used as the bearer token on *some* Google APIs.

I am using a back end server that abides by the OAuth protocol and thus does not know or use JWTs.  I would like to receive the OAuth Access Token under both iOS and Android implementations.

**To Reproduce**
```
user = new UserModel();

GoogleResponse<GoogleUser> googleUser = await _googleClientManager.LoginAsync();

user.Name = googleUser.Data.Name;
user.EmailId = googleUser.Data.Email;
user.Picture = googleUser.Data.Picture.ToString();
user.Provider = "google";
user.ProviderId = googleUser.Data.Id;
user.ProviderToken = CrossGoogleClient.Current.ActiveToken;
```

**Supporting Documentation**
Google API Docs for GoogleSignInAccount show that [getIdToken()](https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil.html#getToken(android.content.Context,%20android.accounts.Account,%20java.lang.String)) will return a JWT and [getServerAuthCode()](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInAccount.html#getServerAuthCode()) will return a "one-time server auth code to send to your web server which can be exchanged for access token".

**Comment by natsoragge** [comment]
I'm having the same problem, but I need JWT for Android and iOS instead of the access token. 😕 It would be nice if we could have both tokens.

**Comment by briandotdev** [comment]
In my mind there should be a method for each.

I come from the world of interpreted languages where I can just dive into the dependency code and start playing around.  I tried to pull down the source and figure out how to get my own locally compiled Nuget  package working but couldn't figure it out.

If someone out there knows how and wants to submit a PR for this I'd be grateful.  Otherwise if no action on this thread I will probably go directly with Xamarin.Auth.

**Comment by natsoragge** [comment]
You can download the code direct from Github if you want to. Just extract the Shared folder to your PCL project and the specific GoogleClientManager to each platform.  This way you'll be able to make the changes you need. Uninstall the Nuget package to avoid conflicts and install any needed dependency (in my case, I needed Xamarin.GooglePlayServices.Auth for Android and Xamarin.Google.iOS.SignIn for iOS)

**Comment by maxyhi** [comment]
has there been a update on this issue?

**Comment by Pujolsluis** [comment]
Hey Guys! 

I agree, this would be a nice improvement for the plugin, and I would love to review and go over the PR once you have this going, @briandotdev as @natsoragge explained you can simply download the project and add the managers to a test Xamarin project and test your changes there, once you have the new methods going you can modify your forked project and shoot a PR from GitHub (:

**Comment by vincentcastagna** [comment]
@Pujolsluis 

So what I understand (and see from the existing code) we cannot retrieve the OAuthCode from the actual implementation of your plugin, meaning, this plugin can only be used to Authenticate user through app mobile, w/o back end process...

 I'm trying to run the project, but I have some issues when rebuilding it with nuget restore. "Cannot load details for GoogleClient" => nuget package restore failed. 

I'd like to do a PR to expose the OAuthCode.
