### ISSUE TITLE
Could not register the assembly 'Plugin.GoogleClient': System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [CrossGeeks/GoogleClientPlugin#42]
**Describe the bug**
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Could not register the assembly 'Plugin.GoogleClient': System.ArgumentNullException: Value cannot be null.

**Desktop (please complete the following information):**
 - OS: iOS 13.1
 - Plugin version: 1.1.1

**Comment by flatplanetpl** [comment]
For now you can downgrade your package xamarin.google.ios.signin to 4.4.0

**Comment by nguyenthanhliemfc** [comment]
@flatplanetpl Its worked, Thank you!

**Comment by xamarindevelopervietnam** [comment]
any ETA for this issue? thanks!

**Comment by xamarindevelopervietnam** [comment]
@rdelrosario @Pujolsluis

**Comment by angelru** [comment]
`CrossGoogleClient.Current` is null

**Comment by rdelrosario** [comment]
Hi if anyone keep having this issue please try the beta version: https://www.nuget.org/packages/Plugin.GoogleClient
