### ISSUE TITLE
After login the onlogin event is calling no of times

### ISSUE THREAD

**Issue by ukt527769275** [CrossGeeks/GoogleClientPlugin#44]
**Describe the bug**

**To Reproduce**
1. Go to 'On login task'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pujolsluis** [comment]
Hello,

Please fill out the issue template correctly or I will have to close this issue.

Thanks

**Comment by rdelrosario** [comment]
This issue isn't clear please open a new one with more details if still having the issue
