### ISSUE TITLE
VS2019 Cannot compile 

### ISSUE THREAD

**Issue by maurosampietro** [CrossGeeks/GoogleClientPlugin#45]
I simply download and open the solution with Visual Studio 2019.
The solution does not compile. 
Sdk dependencies cannot be loaded.

Maybe something changed in the layout of the project file.

**Comment by luizvnegrini** [comment]
Same error here

**Comment by luizvnegrini** [comment]
When running the project and requesting the installation of Xamarin.Google.iOS.SignIn, whether installing manually or with problem persists with an endless error, I followed several steps to fix by installing some packages manually and nothing resolves the bug stack. Does anyone know how to fix? I rolled back to version 4.4.0 and the bugs change, but still do not build. I am running the most current Xamarin packages.

**Comment by rdelrosario** [comment]
This seems to be an environment issue, but you can try beta version https://www.nuget.org/packages/Plugin.GoogleClient/2.0.18-beta
