### ISSUE TITLE
Java.Lang.ClassNotFoundException: 'com.google.android.gms.auth.api.Auth'

### ISSUE THREAD

**Issue by Midnayt** [CrossGeeks/GoogleClientPlugin#46]
**Describe the bug**
Java.Lang.ClassNotFoundException: 'com.google.android.gms.auth.api.Auth'

**To Reproduce**
1. Copy Sample project
2. Run

**Comment by rdelrosario** [comment]
This seems to be an issue related to your environment. Try removing clearing the nuget cache.

**Comment by Midnayt** [comment]
> This seems to be an issue related to your environment. Try removing clearing the nuget cache.

Nope. It is not issue in my environment! If there is no logined google account on device, your Plugin return this error and app will crash. You didn't catch this issue in your Plugin.

**Comment by rdelrosario** [comment]
Try this version: https://www.nuget.org/packages/Plugin.GoogleClient/2.0.18-beta

Let me know if you keep having this issue
