### ISSUE TITLE
iOS social login permission alert.

### ISSUE THREAD

**Issue by scanpay-io** [CrossGeeks/GoogleClientPlugin#49]
Plugin.GoogleClient does not function properly after iOS social login permission alert.  It works well on Android devices.  on iOS, after clicking on Continue for social login permission, it flickers and does nothing.

Steps to reproduce:
Install app on iOS device (iPhone).  Assuming instructions were followed for this nuget package.  Build and deploy the iOS app.  Launch the app and select Google login.  You will be prompted by iOS for permission for social login.  Select "Continue" and it flickers and hangs after couple login attempts.

The expected behavior is that it should follow that of Android device. 

 - Device: Phone6
 - OS: iOS 12.4.6

**Comment by rdelrosario** [comment]
Hi, not sure which version you were trying. But please test on latest
