### ISSUE TITLE
Update Xamarin.Google.iOS.SignIn dependency to the 5.0.2.1 version and make it work.

### ISSUE THREAD

**Issue by Sim-github** [CrossGeeks/GoogleClientPlugin#52]
Hello

Apple is starting to refuse any application containing a reference to the class UIWebview. The Xamarin.Google.iOS.SignIn package had such a reference until the last update to version 5.0.2.1.

I tried to add it in my project but unfortunately it seems that your plugin is only compatible with the version 4.X of the Xamarin.Google.iOS.SignIn (either that or I'm dumb and didn't manage to make it work)

If you want your plugin to be usable on iOS you need to make it compatible with the version 5.0.2.1

**Comment by Sim-github** [comment]
After looking at the current code I see that you already updated the dependency to the 5.0.1, so it will not be too much work.

I guess we are just waiting for you to release a new nugget package ;-)

**Comment by MobilyteApps** [comment]
yes the problem is apple rejected Xamarin.Google.iOS.SignIn  and plugin.googleClient for iOS

**Comment by Char0394** [comment]
Updated in latest version
