### ISSUE TITLE
'ISignInUIDelegate' could not be found in xamarin.Google.iOS.Sign to 5.0.2.1

### ISSUE THREAD

**Issue by lijusparkt** [CrossGeeks/GoogleClientPlugin#54]
Hi,
In iOS Getting error ->
 The type or namespace name 'ISignInUIDelegate' could not be found (are you missing a using directive or an assembly reference?) 
After Update  xamarin.Google.iOS.Sign to 5.0.2.1

Plugin.GoogleClient 2.0 needs xamarin.Google.iOS.Sign >= 5.0.2.1

"Can't able to Submit ipa with "Plugin.GoogleClient 1.1.1 " getting error
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview)."

**Comment by rdelrosario** [comment]
Are you using latest version?

**Comment by lijusparkt** [comment]
Hi, @rdelrosario 
Plugin.GoogleClient **2.1.5**
Xamarin.Google.iOS.SignIn **5.0.2.1**

Visual Studio Community 2019 for Mac
Version **8.4.5** (build 19)

Xamarin.Mac
Version: **6.10.0.17** (Visual Studio Community)
Xamarin.iOS
Version: **13.10.0.17** (Visual Studio Community)
Xamarin.Android
Version: **10.1.3.7** (Visual Studio Community)

**Comment by Jefe21054** [comment]
I have troubles in iOS with Google login, i have a Xamarin Forms project and it opens a Web View and it makes the login with google, but never go inside the app just stay at the login page and never kick the code on the Viewmodel like Android. I'm new developing on Xamarin, so need a bit of help please.
