### ISSUE TITLE
exception on release

### ISSUE THREAD

**Issue by alexisVidal29** [CrossGeeks/GoogleClientPlugin#57]
im using xamarin forms, its works fine on debug mode but when i generate the apk file and install on device, it fails with the exception: The google sign in could not completed it's process correctly

**Comment by husseinshaib1** [comment]
have you added the sha-1 of the release key ?

**Comment by alexisVidal29** [comment]
> have you added the sha-1 of the release key ?

i mean my release apk works fine but when i try google login shows that exception, the app works fine only the google login fails

**Comment by rdelrosario** [comment]
What exception are you getting?

**Comment by alexisVidal29** [comment]
> What exception are you getting?

after it shows account for pick up, the exception is: The google sign in could not completed it's process correctly
in debug mode have no problem

**Comment by rdelrosario** [comment]
It seems you have an issue with release configuration did you add the sha1
of the keystore you are using for release in firebase console portal?

**Comment by alexisVidal29** [comment]
excuse can you help with these configuration

**Comment by rdelrosario** [comment]
Are you using a local keystore to sign the apk on release or using
PlayStore auto-signing?

**Comment by alexisVidal29** [comment]
im using a local keystore(ah-doc) i already create on firebase console an android application with the sha1 key

**Comment by rdelrosario** [comment]
To get the SHA1 for the release keystore:

keytool -exportcert -list -v \
-alias <your-key-name> -keystore <path-to-production-keystore>
