### ISSUE TITLE
Plugin.GoogleClient.Shared.GoogleClientBaseException: 10: 

### ISSUE THREAD

**Issue by mihai301196** [CrossGeeks/GoogleClientPlugin#58]
Hello!

I created a package and inside it I used GoogleClientPlugin.
When I work with the package inside the Sample project where I develop the nugets everything works fine, but when I want to test the packege as a nuget in another project I get this error when I try to log in with google:
Exception is: Plugin.GoogleClient.Shared.GoogleClientBaseException: 10: 
at Plugin.GoogleClient.GoogleClientManager.LoginAsync () [0x000cb] in <9a6ffdce03a64aceaeeebe3956587f25>:0 
at [my function]

The solutions I found was to verify the package name or the fingerprint and both of them are ok.
If you can see, the exception doesn't help me because the message it's "10:" and I can't find anything about it on google or in issues.
If you know why I get this error message please help!

Thanks!

**Comment by marciosouzajunior** [comment]
I'm having the same problem. I downloaded the sample project to see if the problem was my code, but it presented the same error.

![erro_client](https://user-images.githubusercontent.com/3470856/86529319-29899900-be86-11ea-9a4b-07a014a30159.PNG)

**Comment by marciosouzajunior** [comment]
> Hello!
> 
> I created a package and inside it I used GoogleClientPlugin.
> When I work with the package inside the Sample project where I develop the nugets everything works fine, but when I want to test the packege as a nuget in another project I get this error when I try to log in with google:
> Exception is: Plugin.GoogleClient.Shared.GoogleClientBaseException: 10:
> at Plugin.GoogleClient.GoogleClientManager.LoginAsync () [0x000cb] in <9a6ffdce03a64aceaeeebe3956587f25>:0
> at [my function]
> 
> The solutions I found was to verify the package name or the fingerprint and both of them are ok.
> If you can see, the exception doesn't help me because the message it's "10:" and I can't find anything about it on google or in issues.
> If you know why I get this error message please help!
> 
> Thanks!

Hi! I fixed the error by doing two things:

1. Add the Android SHA-1 debug key to Firebase. There is one key to debug and other to production:

[https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/keystore-signature?tabs=windows](url)

You can add these to Firebase:

![sha1](https://user-images.githubusercontent.com/3470856/86576372-07a81900-bf4f-11ea-9e96-75cf04e46ca7.png)

2. If you want to enable server auth code, the type needs be "Web application":

[https://developers.google.com/identity/sign-in/android/start-integrating#get_your_backend_servers_oauth_20_client_id](url)
