### ISSUE TITLE
var token = CrossGoogleClient.Current.ActiveToken;

### ISSUE THREAD

**Issue by hosammostafa2011** [CrossGeeks/GoogleClientPlugin#60]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IGoogleClientManager' does not contain a definition for 'ActiveToken' and no accessible extension method 'ActiveToken' accepting a first argument of type 'IGoogleClientManager' could be found (are you missing a using directive or an assembly reference?)	GoogleClientSample.Android, GoogleClientSample.iOS	C:\Users\Downloads\GoogleClientPlugin-master\GoogleClientPlugin-master\samples\GoogleClientSample\GoogleClientSample\ViewModels\LoginPageViewModel.cs	105	Active

**Comment by tamarci** [comment]
I had the same problem. In the recent version of the plugin ActiveToken is called AccessToken. Change the ActiveToken name to this in your code! It should work.
