### ISSUE TITLE
GoogleClientBaseException

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [CrossGeeks/GoogleClientPlugin#61]
after follow all steps this exception occur " GoogleClientBaseException " any help ?!

**Comment by swapnil591** [comment]
Hello @AhmedAdelGadElkareeem  did you find solution of it.

**Comment by swapnil591** [comment]
Added debug and Release key store SHA1 key in firebase settings
But still getting Exception GoogleClientBaseException.

**Comment by nellydcp** [comment]
Also have the same issue even running the sample app. Didn't had this when using a previous version. Are we missing something?

**Comment by swapnil591** [comment]
Sample code of this repo also returning same exception.

Tested on
OS - Android 10

**Comment by hectoryasmany** [comment]
greetings...im having the same issue here..did get any fix?

**Comment by gigimatto88** [comment]
same issue for me

**Comment by gigimatto88** [comment]
It works: corrected the package name and installed the: Visual Studio 2017 Tools > Android > Android SDK Manager > Extras > Google Repository.

**Comment by alexgavru** [comment]
@gigimatto88 can you please detail the steps you made to make it work?

**Comment by gigimatto88** [comment]
I checked the package name in the android project on Google firebase comsole was exactly as in my manifest.xml.
Then, as described in the android setup section, i installed the Google Repository in my Visual Studio which is in Tools > Android > Android SDK Manager > Extras > Google Repository.
I think this kind of errors come from some missing or wrong configuration.

**Comment by alexgavru** [comment]
Thanks for your response, I already had that installed.
In my case, the problem was that I was signing the apk with another keystore and the actual SHA I was using in firebase was wrong. I debugged the nugget and exception 10 means this: https://stackoverflow.com/questions/47437678/why-do-i-get-com-google-android-gms-common-api-apiexception-10
