### ISSUE TITLE
IdToken coming as null

### ISSUE THREAD

**Issue by KalyanInnomick** [CrossGeeks/GoogleClientPlugin#63]

**Comment by LukeBrandon** [comment]
I am having the same issue.  After a successful login, the AccessToken is populated but the IdToken remains null.

**Comment by housecode** [comment]
Add `your_web_client_id` when initialize this library

# For android
`GoogleClientManager.Initialize(this, clientId: "your_web_client_id");`

# For iOS
`GoogleClientManager.Initialize("your_web_client_id");`

**Comment by LukeBrandon** [comment]
@housecode thanks, that is right.  Wish I saw this documented somewhere a little earlier.

**Comment by Pujolsluis** [comment]
Hi @LukeBrandon,  Please refer to the Getting Started documentation we have a section related to enabling IdToken. Thanks for the support @housecode ! https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/docs/GettingStarted.md
