### ISSUE TITLE
Plugin.GoogleClient.Shared.GoogleClientBaseException: 10

### ISSUE THREAD

**Issue by pedropozzer** [CrossGeeks/GoogleClientPlugin#69]
Hello, I am having an error after logging in since last week.

Plugin.GoogleClient.Shared.GoogleClientBaseException: 10: 
  at Plugin.GoogleClient.GoogleClientManager.LoginAsync () [0x000cb] in <237cfae75d0c48138782e45cf675dd32>:0 

I downloaded the testing application and it has also occurred there.
Tested on several cell phones, different accounts and networks.
Any solution for this error?

![image](https://user-images.githubusercontent.com/11695076/96596724-68235200-12c3-11eb-81be-98d5add09557.jpeg)

**Comment by AnthonyLatty** [comment]
Duplicate: #58
