### ISSUE TITLE
Where and How to put Client ID for Android published version of app?

### ISSUE THREAD

**Issue by muratgny** [CrossGeeks/GoogleClientPlugin#73]
It works perfectly in Android in debug mode. But i don't know how and where to put client id got from Google Console? Maybe I need something else from Google Console? Can you or anyone show that part? In documentation, you provide a link for detailed info, but it is for google maps api. Thanks..

**Comment by Pujolsluis** [comment]
Please refer to the Getting Started Documentation https://github.com/CrossGeeks/GoogleClientPlugin/blob/master/docs/GettingStarted.md
