### ISSUE TITLE
Support Xamarin.Forms 5.0

### ISSUE THREAD

**Issue by gnout** [CrossGeeks/GoogleClientPlugin#77]
**Is your feature request related to a problem? Please describe.**
Seems that GoogleClientPlugin is not compatible with Xamarin.Forms v.5.0 (Android)

**Describe the solution you'd like**
Would it be possible to update GoogleClientPlugin to be compatible with Xamarin.Forms v.5.0 (Android)

**Comment by Alex-Dobrynin** [comment]
Everything works great on android with XF 5

**Comment by gnout** [comment]
Yes, correct. I guess that the project structure was a bit old and that was causing the issues. As soon as a created a new project the library is working correctly.
