### ISSUE TITLE
I want to have google id as well in googleUser class. which is not included right now. How can i have that?

### ISSUE THREAD

**Issue by Yashshree** [CrossGeeks/GoogleClientPlugin#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Pujolsluis** [comment]
Hey @Yashshree ,

This enhancement has been requested already on issue #2 , and we are working on adding it to the plugin. it should be added completely on the next few releases I will tag you on the release where it's added. For now, you can use a Property that is Available on the latest pre-release packages of the plugin called ActiveToken.

**Comment by stealthcold** [comment]
Hi @Pujolsluis !

Is it possible to get the user ID? Didn't find this property in GoogleUser class.

Thanks in advance

**Comment by Pujolsluis** [comment]
Hey @stealthcold ,

Yes we have added that on the lastest release of the plugin you can use an available property called ActiveToken.
